### ISSUE TITLE
Packaged release does not work on Mac OS El capitan (version 10.11.6)

### ISSUE THREAD

**Issue by juraseg** [yue/wey#44]
I downloaded latest release (v0.1.1) and unzipped it, but for some reason the app won't launch. I'm getting error message:
"You can’t open the application “Wey.app” because it may be damaged or incomplete."

I also tried previous release (v0.1.0) and got the same error message.

Not sure, what's causing the issue. Let me know if you need more information.

**Comment by zcbenz** [comment]
I have no idea of this, I probably have to install a copy of macOS 10.11 to know more about it.

**Comment by juraseg** [comment]
An update on this.
When I go into package contents ("Show contents" -> "Wey.app" -> "Contents" -> "MacOS") and run "Wey" in it then it works fine.

Unfortunately I don't know much about MacOS applications packaging, so don't know how to debug this.

**Comment by Lordshinjo** [comment]
I'm getting a similar behavior on Mojave using a case-sensitive partition.
Running it via terminal shows `The application cannot be opened because its executable is missing.`

The binary in the package is named `Wey`, while `Info.plist` contains the following:
```xml
  <key>CFBundleExecutable</key>
  <string>wey</string>
```
Changing `wey` to `Wey` fixes the issue.
